import json
from pathlib import Path
from typing import Any
import pandas as pd

def write_json(file_path: Path | str, data: Any) -> None:
    """
    Writes a Python dictionary or list to a JSON file.
    Automatically creates parent directories if they don't exist.
    """
    # Ensure the path is a Path object
    path = Path(file_path)
    
    # Create the directory structure if it's missing
    path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write the data to the JSON file
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

import pandas as pd

def summary_metrics(df: pd.DataFrame) -> dict[str, float]:
    """
    Calculates the mean (average) for each Ragas metric across all test cases
    in the evaluation DataFrame.
    """
    # These are the standard column names generated by the Ragas library
    target_metrics = [
        "faithfulness", 
        "answer_relevancy", 
        "context_precision", 
        "context_recall"
    ]
    
    summary = {}
    
    for metric in target_metrics:
        # Check if the metric actually exists in the DataFrame to avoid KeyError
        if metric in df.columns:
            # Calculate the mean and round to 4 decimal places for clean reporting
            summary[metric] = round(float(df[metric].mean()), 4)
        else:
            # Fallback if a specific metric failed or wasn't run
            summary[metric] = 0.0
            
    return summary